### ISSUE TITLE
/data is not included on npm

### ISSUE THREAD

**Issue by coderofsalvation** [mugendi/quantities#1]
Hi could you publish this packafge *with* the data-folder?
If i install this package on npm, it won't have the data-folder included (breaking modules which depend on this module)

thx

**Comment by coderofsalvation** [comment]
oh wait this is a fork..nvm

**Comment by mugendi** [comment]
Will try republish with the data folder. Meanwhile, you could get it from this repo. Didn't note that the data folder was missing on npm btw.

**Comment by coderofsalvation** [comment]
Thank you for the comment.  Greetings from hundreds hungary/europe
